### ISSUE TITLE
你好，可以帮下忙吗？

### ISSUE THREAD

**Issue by summersyou** [amu1680c/Y470-Hackintosh#1]
我看到了您在远景论坛的帖子，但是我没有账号，我有一台y470也是升级了处理器，但是我不会装黑苹果，能否留下您的邮箱或者是qq号，帮忙指导一下，谢谢！

**Comment by amu1680c** [comment]
参考[这个](https://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1910185&highlight=%BB%D6%B8%B4)
需要提醒的是，y470本身不支持uefi，需要手动创建模拟efi引导方式
