### ISSUE TITLE
Opencore模拟启动无法使用键盘鼠标

### ISSUE THREAD

**Issue by Dreamkeeper66666** [amu1680c/Y470-Hackintosh#3]
Hello大佬！ 请教一下，我用Opencore模拟UEFI启动后发现键盘鼠标无法选择启动项，Clover没有这个问题，请问您有好的解决方法吗。之前Clover版本的EFI好像找不到了😂😂 @amu1680c

**Comment by amu1680c** [comment]
这个是驱动没设置好，自己调整一下uefi项里面加载的驱动，因为我一直都是键盘操作，没太在意。确实有些小bug

**Comment by Dreamkeeper66666** [comment]
> 这个是驱动没设置好，自己调整一下uefi项里面加载的驱动，因为我一直都是键盘操作，没太在意。确实有些小bug

可以启动了，不过启动后键盘似乎无法驱动。   用OC模拟UEFI启动后USB也挂了，Clover是正常的。。。

**Comment by amu1680c** [comment]
这是OC的bug，用oc0.6版本以前的locagy boot模拟就行了
